GET http://localhost:8080/test/api/cart
Content-Type: application/json
### Sepeti Görüntüle
#[
#  {
#    "cartId": {
#      "cartId": 2,
#      "total": 14000000.00,
#      "ordered": 0
#    },
#    "productId": {
#      "productId": 1,
#      "image": null,
#      "title": "ürün",
#      "description": null,
#      "basePrice": 500000.00,
#      "baseDiscount": 0,
#      "avgRating": 3.5,
#      "sellerId": 1,
#      "discountedPrice": 500000.00,
#      "bought": 0
#    },
#    "quantity": 4,
#    "totalPrice": 2000000.00,
#    "couponCode": null
#  },
#  {
#    "cartId": {
#      "cartId": 2,
#      "total": 14000000.00,
#      "ordered": 0
#    },
#    "productId": {
#      "productId": 2,
#      "image": null,
#      "title": "ürün",
#      "description": null,
#      "basePrice": 500000.00,
#      "baseDiscount": 0,
#      "avgRating": null,
#      "sellerId": 1,
#      "discountedPrice": 500000.00,
#      "bought": 0
#    },
#    "quantity": 8,
#    "totalPrice": 4000000.00,
#    "couponCode": null
#  }
#]
POST http://localhost:8080/test/api/cart
Content-Type: application/json

{
  "product": {"productId":  9},
  "quantity" :8,
  "coupon": null
}
### Sepete Ekle
# STATUS=201(Created)
DELETE http://localhost:8080/test/api/cart
### Sepeti temizle
# 202 (Accepted)
GET http://localhost:8080/test/api/invoice?email=ad@asd.com
### Kayıtlı olmayan kullanıcının siparişleri (email parametre)
GET http://localhost:8080/test/api/invoice
### Kayıtlı kullanıcı siparişleri
# {
#  "invoiceId": 10,
#  "cartId": {
#    "cartId": 22,
#    "total": 2500000.00,
#    "ordered": 1
#  },
#  "dateOrdered": 1702220141000,
#  "invoiceStatus": "InProgress",
#  "paymentMethod": "onlineCard",
#  "deliveryAddress": "adress",
#  "paid": 2500000.00
#}
POST http://localhost:8080/test/api/invoice
Content-Type: application/json

{
  "deliveryAddress": {
    "city": "trabzon",
    "street": "Kalkınma",
    "buildingNo": "13",
    "innerDoorNo": "15"},
  "paymentMethod": "OnlineCard",
  "unregEmail": "ad@asd.com"
}
### kayıtsız müşteri için sepeti satın al
# 201

POST http://localhost:8080/test/api/invoice
Content-Type: application/json

{
  "deliveryAddress": {
    "city": "Trabzon",
  "street": "Konaklar",
  "buildingNo": "14",
  "innerDoorNo": "12"},
  "paymentMethod": "OnlineCard"
}
### Kayıtlı müşteri için sepeti satın al
# 201
PUT http://localhost:8080/test/api/invoice/63
Content-Type: application/json

{
  "deliveryAddress" : {
    "city": "trabzon",
    "street": "Kalkınma",
    "buildingNo": "13",
    "innerDoorNo": "15"},
  "paymentMethod" : "OnlineCard",
  "invoiceStatus": "Complete"
}
### Siparişi güncelleme
# eğer güncellenen siparişin status'u "Completed" veya "Canceled" ise 409
# eğer sipariş hali hazırda OnlineCard methodu ile ödenmiş ise 406
# başırılı ise 202
DELETE http://localhost:8080/test/api/invoice/63
### siparişi iptal et