POST http://localhost:8080/test/api/login
Content-Type: application/json

{
  "email": "ghgfhf@qwe.com",
  "credential": "asdsadsa213123"
}
### Giriş yap
# Kullanıcı bulunamzsa 404, varse anasayfaya yönlendirir ("/")

DELETE http://localhost:8080/test/api/login
Content-Type: application/json
### Çıkış yap
# 200