GET http://localhost:8080/test/api/product
Content-Type: application/json
### tüm ürünleri görüntüle
GET http://localhost:8080/test/api/product?baseDiscountLow>0
### Tüm ürünler, arama parametreleriyle birlikte
GET http://localhost:8080/test/api/product/1
### Ürün sayfası (productId yerine ürün id'si gelmeli)
# {
#  "productId": 1,
#  "image": null,
#  "title": "ürün",
#  "description": null,
#  "basePrice": 500000.00,
#  "baseDiscount": 0,
#  "avgRating": 3.5,
#  "sellerId": 1,
#  "discountedPrice": 500000.00,
#  "bought": 0
#}
GET http://localhost:8080/test/api/product/1/image
Accept: image/jpeg
### Ürün resmi
# binary formatta ürün resmi
GET http://localhost:8080/test/api/product/1/rating
### Ürün değerlendirmeleri
# [
#  {
#    "ratingId": 1,
#    "productId": {
#      "productId": 1,
#      "image": null,
#      "title": null,
#      "description": null,
#      "basePrice": null,
#      "baseDiscount": 0,
#      "avgRating": null,
#      "sellerId": 0,
#      "discountedPrice": null,
#      "bought": 0
#    },
#    "firstName": "ahmet",
#    "lastName": "özer",
#    "dateRated": 1702207245000,
#    "rate": 3.0,
#    "comment": null,
#    "authenticated": 1,
#    "answer": null,
#    "upCount": 1,
#    "downCount": 0,
#    "cookieId": 1
#  },
#  {
#    "ratingId": 9,
#    "productId": {
#      "productId": 1,
#      "image": null,
#      "title": null,
#      "description": null,
#      "basePrice": null,
#      "baseDiscount": 0,
#      "avgRating": null,
#      "sellerId": 0,
#      "discountedPrice": null,
#      "bought": 0
#    },
#    "firstName": "ahmet",
#    "lastName": "özer",
#    "dateRated": 1702220473000,
#    "rate": 4.0,
#    "comment": "good",
#    "authenticated": 1,
#    "answer": null,
#    "upCount": 0,
#    "downCount": 0,
#    "cookieId": 3
#  }
#]
POST http://localhost:8080/test/api/product/4/rating
Content-Type: application/json
Content-Encoding: utf-8

{
  "rate": 3.5,
  "comment": "good",
  "firstName": "isim",
  "lastName": "soyisim"
}
###
POST http://localhost:8080/test/api/product/3/rating
Content-Type: application/json
Content-Encoding: utf-8

{
  "rate": 3.5,
  "comment": "good"
}
### Ürün değerlendir
# Aynı kişi daha önce değerlendirme yaptıysa 409 değilse 201
POST http://localhost:8080/test/api/product/1/rating/9/vote
Content-Type: application/json
Content-Encoding: utf-8

{
  "vote": "DOWN"
}
### Değerlendirme oyla (varolan oyu değiştirmek için de bu isteği kullan)
# 202
PUT http://localhost:8080/test/api/product/1/rating/1
Content-Type: application/json
Content-Encoding: utf-8

{
  "rate": 1.0,
  "comment": "bad"
}
### değerlendirmeyi değiştir
# 202
DELETE http://localhost:8080/test/api/product/1/rating/1
Content-Encoding: utf-8
### Değerlendirmeyi sil
# 202