GET http://localhost:8080/test/api/cart
Content-Type: application/json
Cookie: cartId=2
### Sepeti Görüntüle
#[
#  {
#    "cartId": {
#      "cartId": 2,
#      "total": 14000000.00,
#      "ordered": 0
#    },
#    "productId": {
#      "productId": 1,
#      "image": null,
#      "title": "ürün",
#      "description": null,
#      "basePrice": 500000.00,
#      "baseDiscount": 0,
#      "avgRating": 3.5,
#      "sellerId": 1,
#      "discountedPrice": 500000.00,
#      "bought": 0
#    },
#    "quantity": 4,
#    "totalPrice": 2000000.00,
#    "couponCode": null
#  },
#  {
#    "cartId": {
#      "cartId": 2,
#      "total": 14000000.00,
#      "ordered": 0
#    },
#    "productId": {
#      "productId": 2,
#      "image": null,
#      "title": "ürün",
#      "description": null,
#      "basePrice": 500000.00,
#      "baseDiscount": 0,
#      "avgRating": null,
#      "sellerId": 1,
#      "discountedPrice": 500000.00,
#      "bought": 0
#    },
#    "quantity": 8,
#    "totalPrice": 4000000.00,
#    "couponCode": null
#  }
#]
POST http://localhost:8080/test/api/cart
Content-Type: application/json
Cookie: cartId=2

{
  "productId": 9,
  "quantity" : 2,
  "couponCode": null
}
### Sepeti Görüntüle

PUT http://localhost:8080/test/api/cart
Content-Type: application/json
Cookie: cartId=2

{
  "productId" : 9,
  "quantity": 0,
  "couponCode": null
}
### Sepete Ekle (daha önce sepette bulunmayan)
# STATUS=201(Created)
DELETE http://localhost:8080/test/api/cart
Cookie: cartId=2
### Sepeti temizle
# 202 (Accepted)
GET http://localhost:8080/test/api/invoice?email=asd@qwe.com
### Kayıtlı olmayan kullanıcının siparişleri (email parametre)
GET http://localhost:8080/test/api/invoice
### Kayıtlı kullanıcı siparişleri
# {
#  "invoiceId": 10,
#  "cartId": {
#    "cartId": 22,
#    "total": 2500000.00,
#    "ordered": 1
#  },
#  "dateOrdered": 1702220141000,
#  "invoiceStatus": "InProgress",
#  "paymentMethod": "onlineCard",
#  "deliveryAddress": "adress",
#  "paid": 2500000.00
#}
POST http://localhost:8080/test/api/invoice
Content-Type: application/json

{
  "deliveryAddress": "adres",
  "paymentMethod": "onlineCard",
  "unregEmail": "asd@asd.com"
}
### kayıtsız müşteri için sepeti satın al
# 201

POST http://localhost:8080/test/api/invoice
Content-Type: application/json

{
  "deliveryAddress": "adres",
  "paymentMethod": "OnlineCard"
}
### Kayıtlı müşteri için sepeti satın al
# 201
PUT http://localhost:8080/test/api/invoice
Content-Type: application/json

{
  "deliveryAddress" : "newAddress",
  "paymentMethod" : "OnlineCard",
  "invoiceStatus" : "Canceled"
}
### Siparişi güncelleme
# eğer güncellenen siparişin status'u "Completed" veya "Canceled" ise 409
# eğer sipariş hali hazırda OnlineCard methodu ile ödenmiş ise 406
# başırılı ise 202
DELETE http://localhost:8080/test/api/invoice/1
### siparişi iptal et
GET http://localhost:8080/test/api/product/1
### Ürün sayfası (productId yerine ürün id'si gelmeli)
# {
#  "productId": 1,
#  "image": null,
#  "title": "ürün",
#  "description": null,
#  "basePrice": 500000.00,
#  "baseDiscount": 0,
#  "avgRating": 3.5,
#  "sellerId": 1,
#  "discountedPrice": 500000.00,
#  "bought": 0
#}
GET http://localhost:8080/test/api/product/1/image
Accept: image/jpeg
### Ürün resmi
# binary formatta ürün resmi
GET http://localhost:8080/test/api/product/1/rating
### Ürün değerlendirmeleri
# [
#  {
#    "ratingId": 1,
#    "productId": {
#      "productId": 1,
#      "image": null,
#      "title": null,
#      "description": null,
#      "basePrice": null,
#      "baseDiscount": 0,
#      "avgRating": null,
#      "sellerId": 0,
#      "discountedPrice": null,
#      "bought": 0
#    },
#    "firstName": "ahmet",
#    "lastName": "özer",
#    "dateRated": 1702207245000,
#    "rate": 3.0,
#    "comment": null,
#    "authenticated": 1,
#    "answer": null,
#    "upCount": 1,
#    "downCount": 0,
#    "cookieId": 1
#  },
#  {
#    "ratingId": 9,
#    "productId": {
#      "productId": 1,
#      "image": null,
#      "title": null,
#      "description": null,
#      "basePrice": null,
#      "baseDiscount": 0,
#      "avgRating": null,
#      "sellerId": 0,
#      "discountedPrice": null,
#      "bought": 0
#    },
#    "firstName": "ahmet",
#    "lastName": "özer",
#    "dateRated": 1702220473000,
#    "rate": 4.0,
#    "comment": "good",
#    "authenticated": 1,
#    "answer": null,
#    "upCount": 0,
#    "downCount": 0,
#    "cookieId": 3
#  }
#]
POST http://localhost:8080/test/api/product/1/rating
Content-Type: application/json
Content-Encoding: utf-8

{
  "rate": 3.0,
  "comment": "good",
  "firstName": "Hi!",
  "lastName": "Bruh"
}
### Ürün değerlendir
# Aynı kişi daha önce değerlendirme yaptıysa 409 değilse 201
POST http://localhost:8080/test/api/product/1/rating/1/vote
Content-Type: application/json
Content-Encoding: utf-8

{
  "vote": "up"
}
### Değerlendirme oyla (varolan oyu değiştirmek için de bu isteği kullan)
# 202
PUT http://localhost:8080/test/api/product/1/rating/1
Content-Type: application/json
Content-Encoding: utf-8

{
  "rate": 1.0,
  "comment": "bad"
}
### değerlendirmeyi değiştir
# 202
DELETE http://localhost:8080/test/api/product/1/rating/1
Content-Encoding: utf-8
### Değerlendirmeyi sil
# 202
GET http://localhost:8080/test/api/product
Content-Type: application/json
### tüm ürünleri görüntüle
GET http://localhost:8080/test/api/product?basePriceHigh=100
### Tüm ürünler, arama parametreleriyle birlikte