package com.may.simpleecommercesite.entities;

import com.may.simpleecommercesite.annotations.*;

import java.io.Serializable;
import java.util.List;
import java.util.Objects;

@Entity
public class Cart implements Serializable {
     @Id
     @AutoGenerated
     @Cookie
     int cartId;
      java.math.BigDecimal total;
      boolean ordered;
     @OneToMany(joinColumn = "cartId")
     List<Sale> sales;
    // Empty constructor
    public Cart() {
    }
    // Constructors for combinations of fields that don't have  annotation
    public Cart(int cartId) {
        this.cartId = cartId;
    }
    // Getters and setters (including dirty flags)
    public int getCartId() {
        return cartId;
    }
    public void setCartId(int cartId) {
        this.cartId = cartId;
    }
    public java.math.BigDecimal getTotal() {
        return total;
    }
    public void setTotal( java.math.BigDecimal total) {
        this.total = total;
    }
    public boolean isOrdered() {
        return ordered;
    }
    public void setOrdered(boolean ordered) {
        this.ordered = ordered;
    }
    public List<Sale> getSales(){
        return this.sales;
    }
    public void setSales(List<Sale> sales) {
        this.sales = sales;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || !getClass().isAssignableFrom(o.getClass())) return false;

        Cart cart = (Cart) o;

        return Objects.equals(getCartId(), cart.getCartId());
    }
    @Override
    public int hashCode() {
        return Objects.hash(cartId);
    }
}
