package com.may.simpleecommercesite.entities;

import com.may.simpleecommercesite.annotations.*;

import java.util.List;
@Entity
@Metadata
public class Category {
    @Id
    @AutoGenerated
            @Column(name = "categoryId")
    int id;
    @ManyToOne(joinColumn = "parent")
    Category parent;
    String name;
    @OneToMany(inverseJoinColumn = "parent")
    List<Category> subCategories;
   public Category(){}
    public Category(int id){
       this.id = id;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Category getParent() {
        return parent;
    }

    public void setParent(Category parent) {
        this.parent = parent;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<Category> getSubCategories() {
        return subCategories;
    }

    public void setSubCategories(List<Category> subCategories) {
        this.subCategories = subCategories;
    }
}
