package com.may.simpleecommercesite.entities;

import com.may.simpleecommercesite.annotations.*;
import com.may.simpleecommercesite.entities.embedded.Address;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

@Entity
public class Customer implements Serializable {
     @Cookie
     @Id
     @Column(name = "customerId")
     @AutoGenerated
     int id;
     String email;
     String password;
     String firstName;
     Date birthDate;
     String lastName;
     Address address;
     @NotNull
     @OneToOne(joinColumn = "cartId")
     Cart cart;
     // Empty constructor
    public Customer() {}
    // Constructor for required fields
    public Customer(String firstName, String lastName, String email, String password, Timestamp birthDate){
    this.firstName=firstName;
    this.lastName=lastName;
    this.email=email;
    this.password = password;
    this.birthDate = birthDate;
    }
    public Customer(String email, String password){
        this.email=email;
        this.password = password;
    }
    public Customer(String email) {
        this.email=email;
    }
    public Customer(int id){this.id = id;}
    // Getters and setters (including dirty flags)
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    
    public String getEmail() {
        return email;
    }

    public void setEmail( String email) {
        this.email = email;
    }

    public Date getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName( String firstName) {
        this.firstName = firstName;
    }

    
    public String getLastName() {
        return lastName;
    }

    public void setLastName( String lastName) {
        this.lastName = lastName;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public Address getAddress() {
        return address;
    }

    public Cart getCart() {
        return cart;
    }
    public void setCart(Cart cart) {
        this.cart = cart;
    }

    // Equals and hashCode methods

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || !getClass().isAssignableFrom(o.getClass())) return false;

        Customer customer = (Customer) o;

        return getId()==customer.getId();
    }

    @Override
    public int hashCode() {
        return Integer.hashCode(id);
    }
}

