package com.may.simpleecommercesite.entities;


import com.may.simpleecommercesite.annotations.*;
import com.may.simpleecommercesite.entities.embedded.Address;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Objects;
@Entity
public class Invoice implements Serializable {
    @Id
    @AutoGenerated
     int invoiceId;
    @OneToOne(joinColumn = "cartId")
     Cart cart;
     Timestamp dateOrdered;
     Status invoiceStatus=Status.InProgress;
     PaymentMethod paymentMethod;
     Address deliveryAddress;
     BigDecimal paid;
     @ManyToOne(joinColumn = "email")
     RegisteredCustomer customer;
     String unregEmail;

    public Invoice(){}
    public Invoice(int invoiceId){
        this.invoiceId=invoiceId;
    }
    public Cart getCart() {
        return (Cart) cart;
    }
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Timestamp getDateOrdered() {
        return dateOrdered;
    }
    public void setDateOrdered(Timestamp dateOrdered) {
        this.dateOrdered = dateOrdered;
    }
    public Status getInvoiceStatus() {
        return invoiceStatus;
    }

    public void setInvoiceStatus( Status invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }
    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }
    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public Address getDeliveryAddress() {
        return deliveryAddress;
    }

    public void setDeliveryAddress(Address deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    
    public BigDecimal getPaid() {
        return paid;
    }

    public void setPaid( BigDecimal paid) {
        this.paid = paid;
    }

    public int getInvoiceId() {
        return invoiceId;
    }

    public void setInvoiceId(int invoiceId) {
        this.invoiceId = invoiceId;
    }

    
    public RegisteredCustomer getCustomer() {
        return customer;
    }

    public void setCustomer(RegisteredCustomer customer) {
        this.customer = customer;
    }

    
    public String getUnregEmail() {
        return unregEmail;
    }

    public void setUnregEmail( String unregEmail) {
        this.unregEmail = unregEmail;
    }

    // Equals and hashCode methods

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || !getClass().isAssignableFrom(o.getClass())) return false;

        Invoice invoice = (Invoice) o;

        return Objects.equals(getCart(), invoice.getCart());
    }

    @Override
    public int hashCode() {
        return Objects.hash(cart, invoiceId);
    }
    public enum PaymentMethod{
        OnlineCard,
        AtDoorCard,
        AtDoorCash
    }
    public enum Status{
        InProgress,
        Complete,
        Canceled
    }
}
