package com.may.simpleecommercesite.entities;


import com.fasterxml.jackson.annotation.JsonFilter;
import com.may.simpleecommercesite.annotations.*;
import com.may.simpleecommercesite.entities.embedded.Address;

import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import java.util.Objects;
import com.may.simpleecommercesite.entities.Product;
@Entity
@AggregateMember(in = Product.class)
public class Invoice implements Serializable {
    @Id
    @AutoGenerated
            @Column(name = "invoiceId")
     int id;
    @JsonFilter("depth_3")
    @OneToOne(joinColumn = "cartId")
            @NotNull
     Cart cart;
     Date creationDate;
     Status status = Status.InProgress;
     PaymentMethod paymentMethod;
     Address deliveryAddress;
     BigDecimal paid;
     String email;
     @JsonFilter("depth_1")
    @ManyToOne(joinColumn = "customerId")
             @NotNull
     Customer customer;
    public Invoice(){}
    public Invoice(int id){
        this.id = id;
    }
    public Cart getCart() {
        return (Cart) cart;
    }
    public void setCart(Cart cart) {
        this.cart = cart;
    }
    public Date getCreationDate() {
        return creationDate;
    }
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Status getStatus() {
        return status;
    }
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    public void setStatus(Status status) {
        this.status = status;
    }
    public PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }
    public void setPaymentMethod(PaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    public Address getDeliveryAddress() {
        return deliveryAddress;
    }

    public void setDeliveryAddress(Address deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    
    public BigDecimal getPaid() {
        return paid;
    }

    public void setPaid( BigDecimal paid) {
        this.paid = paid;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    
    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    // Equals and hashCode methods

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || !getClass().isAssignableFrom(o.getClass())) return false;

        Invoice invoice = (Invoice) o;

        return Objects.equals(getCart(), invoice.getCart());
    }

    @Override
    public int hashCode() {
        return Objects.hash(cart, id);
    }
    public enum PaymentMethod{
        OnlineCard,
        AtDoorCard,
        AtDoorCash
    }
    public enum Status{
        InProgress,
        Completed,
        Canceled
    }
}
