package com.may.simpleecommercesite.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.may.simpleecommercesite.annotations.*;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

@Entity
public class Product implements Serializable {
    @Id
    @AutoGenerated
     public int productId;
     public byte[] image;
    public String title;
     public String description;
        public BigDecimal basePrice;
     public int baseDiscount;
     public BigDecimal avgRating;
     @OneToOne(joinColumn = "sellerId")
    public Seller seller;
     @JsonIgnore
     @OneToMany(joinColumn = "productId")
     private List<Rating> ratings;
    public   BigDecimal discountedPrice;
     public int bought;
    // Empty constructor
    public Product() {
    }
    public Product(int productId){
        this.productId=productId;
    }
    // Constructor for required fields
    public Product( int productId,  String title,  BigDecimal basePrice,  BigDecimal avgRating,  BigDecimal discountedPrice) {
        this.productId = productId;
        this.title = title;
        this.basePrice = basePrice;
        this.avgRating = avgRating;
        this.discountedPrice = discountedPrice;
    }
    public int getProductId() {
        return productId;
    }
    public void setProductId ( int productId) {
        this.productId = productId;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }
    public List<Rating> getRatings(){
        return this.ratings;
    }
    public void setRatings(List<Rating> ratings){
        this.ratings=ratings;
    }
    public String getTitle() {
        return title;
    }
    public void setTitle( String title) {
        this.title = title;
    }
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }

    
    public BigDecimal getBasePrice() {
        return basePrice;
    }

    public void setBasePrice( BigDecimal basePrice) {
        this.basePrice = basePrice;
    }

    public int getBaseDiscount() {
        return baseDiscount;
    }

    public void setBaseDiscount(int baseDiscount) {
        this.baseDiscount = baseDiscount;
    }

    
    public BigDecimal getAvgRating() {
        return avgRating;
    }

    public void setAvgRating( BigDecimal avgRating) {
        this.avgRating = avgRating;
    }

    public Seller getSeller() {
        return seller;
    }

    public void setSeller(Seller seller) {
        this.seller = seller;
    }

    
    public BigDecimal getDiscountedPrice() {
        return discountedPrice;
    }

    public void setDiscountedPrice( BigDecimal discountedPrice) {
        this.discountedPrice = discountedPrice;
    }

    public int getBought() {
        return bought;
    }

    public void setBought(int bought) {
        this.bought = bought;
    }

    // Equals and hashCode methods

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || !getClass().isAssignableFrom(o.getClass())) return false;

        Product product = (Product) o;

        return getProductId() == product.getProductId();
    }

    @Override
    public int hashCode() {
        return Integer.hashCode(productId);
    }
}
