package com.may.simpleecommercesite.entities;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.may.simpleecommercesite.annotations.*;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Objects;

@Entity
public class Rating implements Serializable {
    @Id
    @AutoGenerated
     int ratingId;
     @JsonIgnore
     @OneToOne(joinColumn = "productId")
    Product product;
     String firstName;
     String lastName;
     Timestamp dateRated;
     BigDecimal rate;
     String comment;
     boolean authenticated;
     String answer;
     int upCount;
     int downCount;
     @Cookie
     int cookieId;
    // Empty constructor
    public Rating() {}
    public Rating(int ratingId){
        this.ratingId=ratingId;
    }
    public int getRatingId() {
        return ratingId;
    }
    public void setRatingId(int ratingId) {
        this.ratingId = ratingId;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Timestamp getDateRated() {
        return dateRated;
    }

    public void setDateRated(Timestamp dateRated) {
        this.dateRated = dateRated;
    }

    public BigDecimal getRate() {
        return rate;
    }

    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public boolean isAuthenticated() {
        return authenticated;
    }

    public void setAuthenticated(boolean authenticated) {
        this.authenticated = authenticated;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public int getUpCount() {
        return upCount;
    }

    public void setUpCount(int upCount) {
        this.upCount = upCount;
    }

    public int getDownCount() {
        return downCount;
    }

    public void setDownCount(int downCount) {
        this.downCount = downCount;
    }

    public int getCookieId() {
        return cookieId;
    }

    public void setCookieId(int cookieId) {
        this.cookieId = cookieId;
    }
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || !getClass().isAssignableFrom(o.getClass())) return false;

        Rating rating = (Rating) o;

        return getCookieId() == rating.getCookieId() && Objects.equals(getProduct(), rating.getProduct());
    }

    @Override
    public int hashCode() {
        return Integer.hashCode(ratingId);
    }
}
