package com.may.simpleecommercesite.entities;

import com.may.simpleecommercesite.annotations.*;
import com.may.simpleecommercesite.entities.embedded.Address;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Objects;

@Entity
public class RegisteredCustomer implements Serializable {
     @Cookie
     @Id
     @AutoGenerated
     int cookieId;
     @Id
     String email;
     String credential;
     String firstName;
     Timestamp dateOfBirth;
     String lastName;
     Address address;
     @Cookie
     @OneToOne(joinColumn = "cartId")
     Cart cart;
     // Empty constructor
    public RegisteredCustomer() {}
    // Constructor for required fields
    public RegisteredCustomer(String firstName, String lastName, String email, String credential, Timestamp dateOfBirth){
    this.firstName=firstName;
    this.lastName=lastName;
    this.email=email;
    this.credential=credential;
    this.dateOfBirth=dateOfBirth;
    }
    public RegisteredCustomer(String email, String credential){
        this.email=email;
        this.credential=credential;
    }
    public RegisteredCustomer(String email) {
        this.email=email;
    }
    // Getters and setters (including dirty flags)
    public int getCookieId() {
        return cookieId;
    }

    public void setCookieId(int cookieId) {
        this.cookieId = cookieId;
    }

    
    public String getEmail() {
        return email;
    }

    public void setEmail( String email) {
        this.email = email;
    }

    public Timestamp getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Timestamp dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getCredential() {
        return credential;
    }

    public void setCredential( String credential) {
        this.credential = credential;
    }

    
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName( String firstName) {
        this.firstName = firstName;
    }

    
    public String getLastName() {
        return lastName;
    }

    public void setLastName( String lastName) {
        this.lastName = lastName;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public Address getAddress() {
        return address;
    }

    public Cart getCart() {
        return cart;
    }
    public void setCart(Cart cart) {
        this.cart = cart;
    }

    // Equals and hashCode methods

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || !getClass().isAssignableFrom(o.getClass())) return false;

        RegisteredCustomer customer = (RegisteredCustomer) o;

        return getCookieId()==customer.getCookieId() && Objects.equals(getEmail(), customer.getEmail());
    }

    @Override
    public int hashCode() {
        int result = Integer.hashCode(cookieId);
        result = 31 * result + email.hashCode();
        return result;
    }
}

