package com.may.simpleecommercesite.entities;

import com.may.simpleecommercesite.annotations.AutoGenerated;
import com.may.simpleecommercesite.annotations.Entity;
import com.may.simpleecommercesite.annotations.Id;
import com.may.simpleecommercesite.entities.embedded.Address;

import java.io.Serializable;
@Entity
public class Seller implements Serializable {
    @Id
    @AutoGenerated
     int sellerId;
     String shopName;
     Address address;

    // Constructor for required fields
    public Seller(int sellerId) {
        this.sellerId=sellerId;
    }
    public Seller() {
    }
    // Constructors for combinations of fields that don't have  annotation


    // Getters and setters (including dirty flags)

    public int getSellerId() {
        return sellerId;
    }

    public void setSellerId( int sellerId) {
        this.sellerId = sellerId;
    }

    
    public String getShopName() {
        return shopName;
    }

    public void setShopName( String shopName) {
        this.shopName = shopName;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    // Equals and hashCode methods

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || !getClass().isAssignableFrom(o.getClass())) return false;

        Seller seller = (Seller) o;

        return getSellerId()==seller.getSellerId();
    }

    @Override
    public int hashCode() {
        return Integer.hashCode(sellerId);
    }
}
