insert into customer values ();
select last_insert_id() from customer limit 1 into @custId;
insert into cart values ();
select last_insert_id() from cart limit 1 into @cartId;
insert into coupon (discount, couponId) values (25, !couponId!);
select last_insert_id() from coupon limit 1 into @couponId;
insert into customer (email, password, cartId) values (!username!, !password!, @cartId);
select last_insert_id() from customer limit 1 into @regCustId;
insert into seller (name, address) values (!name!, !address!);
select sellerId from seller limit 1 into @sellerId;
insert into product (title, description, basePrice, sellerId) values ("ürün", "açıklama", 200, @sellerId);
select last_insert_id() from product limit 1 into @productId;
select discountedPrice from product where productId=@productId into @price;
insert into rating(rating, comment, productId) values(2.5, "ok", @productId);
insert into sale (productId, cartId, quantity, price) values (@productId, @cartId, 5, @price);
insert into invoice (couponId, cartId, customerId ) values (!couponId!, @cartId, @regCustId);
insert into rating (rating, comment, productId, customerId) values (3.0, "nice", @productId, @regCustId);